/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AttributeEntryDTO } from '../model/attributeEntryDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AttributeEntryResourceService {

    protected basePath = 'https://localhost:8084';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createAttributeEntry
     * 
     * @param attributeEntryDTO attributeEntryDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createAttributeEntryUsingPOST(attributeEntryDTO: AttributeEntryDTO, observe?: 'body', reportProgress?: boolean): Observable<AttributeEntryDTO>;
    public createAttributeEntryUsingPOST(attributeEntryDTO: AttributeEntryDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AttributeEntryDTO>>;
    public createAttributeEntryUsingPOST(attributeEntryDTO: AttributeEntryDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AttributeEntryDTO>>;
    public createAttributeEntryUsingPOST(attributeEntryDTO: AttributeEntryDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (attributeEntryDTO === null || attributeEntryDTO === undefined) {
            throw new Error('Required parameter attributeEntryDTO was null or undefined when calling createAttributeEntryUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<AttributeEntryDTO>(`${this.basePath}/api/attribute-entries`,
            attributeEntryDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteAttributeEntry
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteAttributeEntryUsingDELETE(id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteAttributeEntryUsingDELETE(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteAttributeEntryUsingDELETE(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteAttributeEntryUsingDELETE(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteAttributeEntryUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/attribute-entries/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllAttributeEntries
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllAttributeEntriesUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<AttributeEntryDTO>>;
    public getAllAttributeEntriesUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AttributeEntryDTO>>>;
    public getAllAttributeEntriesUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AttributeEntryDTO>>>;
    public getAllAttributeEntriesUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<AttributeEntryDTO>>(`${this.basePath}/api/attribute-entries`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAttributeEntry
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAttributeEntryUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<AttributeEntryDTO>;
    public getAttributeEntryUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AttributeEntryDTO>>;
    public getAttributeEntryUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AttributeEntryDTO>>;
    public getAttributeEntryUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getAttributeEntryUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AttributeEntryDTO>(`${this.basePath}/api/attribute-entries/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateAttributeEntry
     * 
     * @param attributeEntryDTO attributeEntryDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateAttributeEntryUsingPUT(attributeEntryDTO: AttributeEntryDTO, observe?: 'body', reportProgress?: boolean): Observable<AttributeEntryDTO>;
    public updateAttributeEntryUsingPUT(attributeEntryDTO: AttributeEntryDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AttributeEntryDTO>>;
    public updateAttributeEntryUsingPUT(attributeEntryDTO: AttributeEntryDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AttributeEntryDTO>>;
    public updateAttributeEntryUsingPUT(attributeEntryDTO: AttributeEntryDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (attributeEntryDTO === null || attributeEntryDTO === undefined) {
            throw new Error('Required parameter attributeEntryDTO was null or undefined when calling updateAttributeEntryUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<AttributeEntryDTO>(`${this.basePath}/api/attribute-entries`,
            attributeEntryDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
