/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AttributeTypeDTO } from '../model/attributeTypeDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AttributeTypeResourceService {

    protected basePath = 'https://localhost:8084';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createAttributeType
     * 
     * @param attributeTypeDTO attributeTypeDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createAttributeTypeUsingPOST(attributeTypeDTO: AttributeTypeDTO, observe?: 'body', reportProgress?: boolean): Observable<AttributeTypeDTO>;
    public createAttributeTypeUsingPOST(attributeTypeDTO: AttributeTypeDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AttributeTypeDTO>>;
    public createAttributeTypeUsingPOST(attributeTypeDTO: AttributeTypeDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AttributeTypeDTO>>;
    public createAttributeTypeUsingPOST(attributeTypeDTO: AttributeTypeDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (attributeTypeDTO === null || attributeTypeDTO === undefined) {
            throw new Error('Required parameter attributeTypeDTO was null or undefined when calling createAttributeTypeUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<AttributeTypeDTO>(`${this.basePath}/api/attribute-types`,
            attributeTypeDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteAttributeType
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteAttributeTypeUsingDELETE(id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteAttributeTypeUsingDELETE(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteAttributeTypeUsingDELETE(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteAttributeTypeUsingDELETE(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteAttributeTypeUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/attribute-types/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllAttributeTypes
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllAttributeTypesUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<AttributeTypeDTO>>;
    public getAllAttributeTypesUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AttributeTypeDTO>>>;
    public getAllAttributeTypesUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AttributeTypeDTO>>>;
    public getAllAttributeTypesUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<AttributeTypeDTO>>(`${this.basePath}/api/attribute-types`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAttributeType
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAttributeTypeUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<AttributeTypeDTO>;
    public getAttributeTypeUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AttributeTypeDTO>>;
    public getAttributeTypeUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AttributeTypeDTO>>;
    public getAttributeTypeUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getAttributeTypeUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<AttributeTypeDTO>(`${this.basePath}/api/attribute-types/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateAttributeType
     * 
     * @param attributeTypeDTO attributeTypeDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateAttributeTypeUsingPUT(attributeTypeDTO: AttributeTypeDTO, observe?: 'body', reportProgress?: boolean): Observable<AttributeTypeDTO>;
    public updateAttributeTypeUsingPUT(attributeTypeDTO: AttributeTypeDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AttributeTypeDTO>>;
    public updateAttributeTypeUsingPUT(attributeTypeDTO: AttributeTypeDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AttributeTypeDTO>>;
    public updateAttributeTypeUsingPUT(attributeTypeDTO: AttributeTypeDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (attributeTypeDTO === null || attributeTypeDTO === undefined) {
            throw new Error('Required parameter attributeTypeDTO was null or undefined when calling updateAttributeTypeUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<AttributeTypeDTO>(`${this.basePath}/api/attribute-types`,
            attributeTypeDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
