/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ImageUrlDTO } from '../model/imageUrlDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ImageUrlResourceService {

    protected basePath = 'https://localhost:8084';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createImageUrl
     * 
     * @param imageUrlDTO imageUrlDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createImageUrlUsingPOST(imageUrlDTO: ImageUrlDTO, observe?: 'body', reportProgress?: boolean): Observable<ImageUrlDTO>;
    public createImageUrlUsingPOST(imageUrlDTO: ImageUrlDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ImageUrlDTO>>;
    public createImageUrlUsingPOST(imageUrlDTO: ImageUrlDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ImageUrlDTO>>;
    public createImageUrlUsingPOST(imageUrlDTO: ImageUrlDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (imageUrlDTO === null || imageUrlDTO === undefined) {
            throw new Error('Required parameter imageUrlDTO was null or undefined when calling createImageUrlUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<ImageUrlDTO>(`${this.basePath}/api/image-urls`,
            imageUrlDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteImageUrl
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteImageUrlUsingDELETE(id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteImageUrlUsingDELETE(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteImageUrlUsingDELETE(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteImageUrlUsingDELETE(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteImageUrlUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/image-urls/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllImageUrls
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllImageUrlsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<ImageUrlDTO>>;
    public getAllImageUrlsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ImageUrlDTO>>>;
    public getAllImageUrlsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ImageUrlDTO>>>;
    public getAllImageUrlsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<ImageUrlDTO>>(`${this.basePath}/api/image-urls`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getImageUrl
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getImageUrlUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<ImageUrlDTO>;
    public getImageUrlUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ImageUrlDTO>>;
    public getImageUrlUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ImageUrlDTO>>;
    public getImageUrlUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getImageUrlUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<ImageUrlDTO>(`${this.basePath}/api/image-urls/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateImageUrl
     * 
     * @param imageUrlDTO imageUrlDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateImageUrlUsingPUT(imageUrlDTO: ImageUrlDTO, observe?: 'body', reportProgress?: boolean): Observable<ImageUrlDTO>;
    public updateImageUrlUsingPUT(imageUrlDTO: ImageUrlDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ImageUrlDTO>>;
    public updateImageUrlUsingPUT(imageUrlDTO: ImageUrlDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ImageUrlDTO>>;
    public updateImageUrlUsingPUT(imageUrlDTO: ImageUrlDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (imageUrlDTO === null || imageUrlDTO === undefined) {
            throw new Error('Required parameter imageUrlDTO was null or undefined when calling updateImageUrlUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<ImageUrlDTO>(`${this.basePath}/api/image-urls`,
            imageUrlDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
