/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UnitDTO } from './unitDTO';


export interface AttributeTypeDTO { 
    dataType?: AttributeTypeDTO.DataTypeEnum;
    id?: number;
    materialIcon?: string;
    name?: string;
    units?: Array<UnitDTO>;
}
export namespace AttributeTypeDTO {
    export type DataTypeEnum = 'TEXT' | 'NUMBER_INTEGER' | 'BOOL' | 'DATE' | 'NUMBER_DECIMAL';
    export const DataTypeEnum = {
        TEXT: 'TEXT' as DataTypeEnum,
        NUMBERINTEGER: 'NUMBER_INTEGER' as DataTypeEnum,
        BOOL: 'BOOL' as DataTypeEnum,
        DATE: 'DATE' as DataTypeEnum,
        NUMBERDECIMAL: 'NUMBER_DECIMAL' as DataTypeEnum
    };
}
