/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttributeEntryDTO } from './attributeEntryDTO';
import { CategoryDTO } from './categoryDTO';
import { ShopDTO } from './shopDTO';


export interface ProductDTO { 
    attributeEntries?: Array<AttributeEntryDTO>;
    brandId?: number;
    brandName?: string;
    categories?: Array<CategoryDTO>;
    currencyId?: number;
    currencySymbol?: string;
    id?: number;
    name?: string;
    previewImageId?: number;
    previewImageUrl?: string;
    price?: number;
    shops?: Array<ShopDTO>;
    subtitle?: string;
}
