/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AttributeEntryDTO } from './attributeEntryDTO';
import { CategoryDTO } from './categoryDTO';
import { ShopDTO } from './shopDTO';


export interface ProductDTO { 
    attributeEntries?: Array<AttributeEntryDTO>;
    brandId?: number;
    categories?: Array<CategoryDTO>;
    id?: number;
    name?: string;
    price?: number;
    shops?: Array<ShopDTO>;
}
